### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by Janpot** [XeCycle/pg-template-tag#1]
##### 1. [`WHERE foo IN (...)` queries](https://github.com/brianc/node-postgres/wiki/FAQ#11-how-do-i-build-a-where-foo-in--query-to-find-rows-matching-an-array-of-values).

Unless I'm overlooking something this problem is still present in your library. Maybe there can be a utility to construct these? Something along the lines of:

``` js
let sql = require('pg-template-tag');

sql.seq = function (array) {
  let parts = ['']
  for (let i = 0; i < array.length - 1; i++) {
    parts.push(',');
  }
  parts.push('');
  return sql.apply(null, [parts].concat(array));
}

let ids = [1, 2, 3];
let q = sql`
  SELECT * FROM users
  WHERE id IN (${sql.seq(ids)})
`

console.log(q.text, q.values);
//  SELECT * FROM users
//  WHERE id IN ($1,$2,$3)
// [ 1, 2, 3 ]
```

Or this might as well be the default handling of arrays as far as I'm concerned.
##### 2. [prepared statements](https://github.com/brianc/node-postgres/wiki/Client#method-query-prepared).

Maybe you could add a method to turn the query in a prepared statement. Something like:

``` js
let q = sql`SELECT * FROM users`.prepare('get-users');

console.log(q.name);
// get-users
```

**Comment by XeCycle** [comment]
1. Flattening an array does not seem so useful to me.  You can use `WHERE id is not distinct from ANY(${array})` instead.  My test on 9.4 server shows no performance difference of the two, both are optimized to index scans.  Btw this conflicts with 2, in that generated `.text` are different for different array lengths.
2. Different `.text` may be generated each time, it would be a potential pitfall.  I'd leave this open for discussion, though I'm personally against it.  It's not hard to keep a function that simply assigns a `.name` in your own code.

**Comment by Janpot** [comment]
no problem

**Comment by Janpot** [comment]
@XeCycle I came across of a few more use cases where a join-like operation could be useful:

``` js
function joinSql(array, separator) {
  separator = separator || ',';
  var parts = [];
  parts.push('');
  for (var i = 0; i < array.length - 1; i++) {
    parts.push(separator);
  }
  parts.push('');
  return sql.apply(null, [parts].concat(array));
}
```

Initialising values for insertion:

``` js
function fillTable(table) {
  var values = joinSql(table.map(function (row) {
    return sql`(${joinSql(row, ',')})`
  }), ',');
  return query(sql`INSERT INTO table VALUES ${values}`);
}

fillTable([
  [1, 'test1@mail.com'],
  [2, 'test2@mail.com'],
  [3, 'test3@mail.com']
]);
```

joining `WHERE` conditions:

``` js
function filterUsers(filter) {
  var conditions = [];
  if (filter.minAge) {
    conditions.push(sql`age > ${filter.minAge}`);
  }
  if (filter.maxAge) {
    conditions.push(sql`age < ${filter.maxAge}`);
  }
  if (filter.email) {
    conditions.push(sql`email LIKE ${filter.email}`);
  }
  return query(sql`
    SELECT * FROM users
    WHERE ${joinSql(conditions, ' AND ')}
  `);
}

filterUsers({
  minAge: 18,
  email: '%@mail.com'
});
```

`Array.prototype.join` is a powerful function for string creation and it would be useful to have an equivalent on `pg-template-tag` strings too. Maybe these examples can convince you of that too.

**Comment by XeCycle** [comment]
Agreed, joining conditions looks reasonable to me.  Can you open a new issue for this?

**Comment by Janpot** [comment]
https://github.com/XeCycle/pg-template-tag/issues/2
