### ISSUE TITLE
Multiline string template query support

### ISSUE THREAD

**Issue by jadbox** [XeCycle/pg-template-tag#6]
It would be awesome to be able to do something like the following, although I know string parsing like this can be problematic:

```
const sql =
`CREATE TABLE vids2
(
  id serial PRIMARY KEY,
  name character varying(255),
  formula character varying(255),
  environment enum_vids_environment DEFAULT 'desktop'::enum_vids_environment,
  "userId" integer NOT NULL,
  CONSTRAINT "vids2_userId_fkey" FOREIGN KEY ("userId")
   REFERENCES users (id) MATCH SIMPLE
   ON UPDATE CASCADE ON DELETE CASCADE
);`;
```
- Open question: how would you write a regex parser to remove any extra spaces for newlines from the query without accidentally modifying values going into a query field itself?

**Comment by XeCycle** [comment]
You mean to remove extra spaces from the query text?  Your example would become

```
CREATE TABLE vids2(id serial PRIMARY KEY,name character varying(255),formula character varying(255),environment enum_vids_environment DEFAULT 'desktop'::enum_vids_environment,"userId" integer NOT NULL,CONSTRAINT "vids2_userId_fkey" FOREIGN KEY("userId")REFERENCES users(id)MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE);
```

which saves <10% size.  The original query (maybe with other parameters) probably fits into one MTU already, so I don't think this can give any significant improvement in response time; after all I'd assume the database is typically connected over domain socket or loopback, or at least a 1GbE link.

> how would you write a regex parser ...

I am not sure whether a single regex can get all done, but luckily we do not need to deal with escapes like `'\''` so a single regex can easily catch all quoted parts.

**Comment by pauldraper** [comment]
Yeah, this isn't a problem.

If it were, you could

```javascript
join(
  SQL`SELECT *`,
  SQL`FROM example`,
  SQL`WHERE id = ${id}`,
)
```
