### ISSUE TITLE
Generic Public Domain License

### ISSUE THREAD

**Issue by ttraenkler** [XeCycle/pg-template-tag#9]
Thanks for this great project. The package is dead simple but does it's job better than most of the more sophisticated projects such as slonik simply by allowing to nest sql fragments and thus use it as a SQL injection safe query builder. 

The only problem I see is that the license of this project SAX-PD refers to the SAX project "Simple Api XML" and thus does not really apply: https://spdx.org/licenses/SAX-PD.html

It would be preferable to replace the SAX-PD with a generic public domain license such as the "Unlicense" referenced here: 
- https://en.wikipedia.org/wiki/Public-domain-equivalent_license 
- https://en.wikipedia.org/wiki/Unlicense

**Comment by XeCycle** [comment]
I see.  Actually I did consider changing to CC0 (~1 year after first release) but was not motivated enough to do it; today, given the problem of SAX-PD, I totally agree with such a change.  Let's see if the other two contributors agree. @Janpot @pauldraper

**Comment by Janpot** [comment]
Seems like [CC0 is not a great choice for software](https://creativecommons.org/2011/04/15/using-cc0-for-public-domain-software/). Do you have any particular aversion against MIT?

**Comment by ttraenkler** [comment]
Not at all. MIT is even better!

**Comment by XeCycle** [comment]
> Seems like CC0 is not a great choice for software.

That page reads like "we did not intend it but FSF recommends it".  But anyway, I have no preference on CC0 vs Unlicense.

> Do you have any particular aversion against MIT?

When I first released this project I intended to dedicate it to public domain; re-licensing to MIT would mean to revoke that dedication, and to add restrictions on users.  I prefer not to make such a substantial change; a simple clarification feels better.

**Comment by Janpot** [comment]
ok for me then 👍

**Comment by ttraenkler** [comment]
I agree if it's already in PD, it may be easier for some users to adapt to a more permissive PD license.

**Comment by ttraenkler** [comment]
Thanks for your openness to clarify the license. CC0 or Unlicense is fine. So the only missing piece is the consent of @pauldraper?

**Comment by ttraenkler** [comment]
It seems @pauldraper does not follow this issue but seems active on Github - could you try to contact him please?

**Comment by ttraenkler** [comment]
@XeCycle @Janpot - do you have any means of contacting @pauldraper to have his opinion on this issue? He seems active on Github and Hackernews - I tried via his e-mail but maybe I landed in the spam folder.

**Comment by XeCycle** [comment]
Have to say I no nothing more about him/her than you do.  If you want it I can add a branch from a commit without his/her code and license that as CC0/Unlicense, which should be safe to use I guess.

**Comment by ttraenkler** [comment]
@XeCycle Sounds good to me, thanks! Since this would not be accessible from NPM I assume I could ship the package with the projects that use it along with the license information?

I could also contribute a function that resubstitutes parameters back into a plain unparameterized SQL query which I use to be able to copy paste built queries into a SQL query tool for testing during development.

**Comment by XeCycle** [comment]
Public domain means you can do practically anything with it, I believe.  IMO you can even copy it without any attribution/license info, sell it for money, etc.

Btw this comment is not a legal grant of use from me.

**Comment by ttraenkler** [comment]
@XeCycle Do you think it's feasible to fork this without the work from @pauldraper? I reviewed the commits and since the library is very short and his commit affect a large percentage of the code, maybe a rewrite is quicker.

**Comment by XeCycle** [comment]
I took a quick glance at those commits and imo most of them are just optimizations and do not affect functionality.  You are free to take any way you like :smile:

**Comment by ttraenkler** [comment]
Thanks for your offer, but in the end management asked us to look into alternatives and we switched our codebase to [sql-template-tag](https://github.com/blakeembrey/sql-template-tag) which provides the same functionality + support for raw sql snippets.

**Comment by XeCycle** [comment]
Glad to hear there's a better maintained alternative.  My current job does not involve js, and I don't think getting my hands on something I do not use is a good thing.  Maybe the community would prefer better maintenance.

**Comment by ttraenkler** [comment]
No problem, thanks for your work!
